# Generated by Django 2.2.1 on 2019-07-30 17:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='公司名称')),
                ('address', models.TextField(verbose_name='公司地址')),
                ('email', models.EmailField(max_length=254, verbose_name='公司邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='类行')),
                ('description', models.TextField(verbose_name='类型描述')),
            ],
        ),
        migrations.CreateModel(
            name='interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('content', ckeditor.fields.RichTextField(verbose_name='内容')),
                ('description', ckeditor.fields.RichTextField(verbose_name='描述')),
                ('Company_interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Company', verbose_name='公司面试题')),
            ],
        ),
    ]
